
import { FormState } from "@/app/types/formState"


export const initialFormState: FormState = {
    errors: {},
    touched: {},
    success: false,
    isSubmitting: false,
    serviceType: null,
    currentStep: 1,
    maxSteps: 3,
    data: {
        name: "",
        email: "",
        phone: "",
        originAddress: "",
        destinationAddress: "",
        description: "",
        value: "",
        weight: "",
        dimensions: "",
        additionalInfo: "",
        companyNameSupplier: "",
        exactPickupAddress: "",
        typeOfService: undefined,
        equipmentNeeded: undefined,
        temperature: "",
        temperatureUnit: undefined,
        cargoInGauge: false,
        cargoDimensions: "",
        dimensionsUnit: "m",
        loadingAssistance: false,
        unloadingAssistance: false,
        packages: "",
        shippingTerm: undefined,
        containerCapacity: 0,
        cargoGaugeType: "in",
        isGeneral: false,
        isHazardous: false,
        cargoType: undefined,
        weightValue: "",
        weightUnit: "kg",
        descriptionOfGoods: "",
    },
}